"""Add UserPlatformInfo and Tag models

Revision ID: 8b401af8a3de
Revises: a4e51a3a0a55
Create Date: 2024-12-10 00:22:37.464403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8b401af8a3de'
down_revision: Union[str, None] = 'a4e51a3a0a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
