"""Add UserPlatformInfo and Tag models

Revision ID: a4e51a3a0a55
Revises: 691d682a2949
Create Date: 2024-12-09 22:20:02.146105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e51a3a0a55'
down_revision: Union[str, None] = '691d682a2949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('userplatforminfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mc_experience', sa.String(), nullable=False),
    sa.Column('play_reason', sa.String(), nullable=False),
    sa.Column('server_type', sa.String(), nullable=False),
    sa.Column('desired_partners', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userplatforminfo_tag_link',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_platform_info_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_platform_info_id'], ['userplatforminfo.id'], ),
    sa.PrimaryKeyConstraint('user_platform_info_id', 'tag_id')
    )
    op.drop_column('user', 'platform_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('platform_info', sa.VARCHAR(), server_default=sa.text("'{}'::character varying"), autoincrement=False, nullable=False))
    op.drop_table('userplatforminfo_tag_link')
    op.drop_table('userplatforminfo')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
