"""3

Revision ID: 043738121688
Revises: 74618804b8ab
Create Date: 2024-12-14 17:47:38.583145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '043738121688'
down_revision: Union[str, None] = '74618804b8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LinkTeamFollow',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('LinkUserFollow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.add_column('Team', sa.Column('followers_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('User', sa.Column('followers_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('User', sa.Column('following_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'following_count')
    op.drop_column('User', 'followers_count')
    op.drop_column('Team', 'followers_count')
    op.drop_table('LinkUserFollow')
    op.drop_table('LinkTeamFollow')
    # ### end Alembic commands ###
