"""5

Revision ID: 694f164681cf
Revises: 2e23ead49b59
Create Date: 2024-12-16 22:37:49.503676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '694f164681cf'
down_revision: Union[str, None] = '2e23ead49b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Identity_name', table_name='Identity')
    op.create_index(op.f('ix_Identity_name'), 'Identity', ['name'], unique=True)
    op.drop_index('ix_Proj_name', table_name='Proj')
    op.create_index(op.f('ix_Proj_name'), 'Proj', ['name'], unique=True)
    op.drop_index('ix_Resource_name', table_name='Resource')
    op.create_index(op.f('ix_Resource_name'), 'Resource', ['name'], unique=True)
    op.drop_index('ix_Team_name', table_name='Team')
    op.create_index(op.f('ix_Team_name'), 'Team', ['name'], unique=True)
    
    op.add_column('User', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # 将旧的 username 数据迁移到新列 name
    op.execute('UPDATE "User" SET name = username')
    
    op.add_column('User', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    
    op.drop_index('ix_User_username', table_name='User')
    op.create_index(op.f('ix_User_name'), 'User', ['name'], unique=True)
    op.drop_column('User', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    # 将新的 name 数据迁移到旧列 username
    op.execute('UPDATE "User" SET username = name')
    
    op.drop_index(op.f('ix_User_name'), table_name='User')
    op.create_index('ix_User_username', 'User', ['username'], unique=True)
    op.drop_column('User', 'description')
    op.drop_column('User', 'name')
    op.drop_index(op.f('ix_Team_name'), table_name='Team')
    op.create_index('ix_Team_name', 'Team', ['name'], unique=False)
    op.drop_index(op.f('ix_Resource_name'), table_name='Resource')
    op.create_index('ix_Resource_name', 'Resource', ['name'], unique=False)
    op.drop_index(op.f('ix_Proj_name'), table_name='Proj')
    op.create_index('ix_Proj_name', 'Proj', ['name'], unique=False)
    op.drop_index(op.f('ix_Identity_name'), table_name='Identity')
    op.create_index('ix_Identity_name', 'Identity', ['name'], unique=False)
    # ### end Alembic commands ###
