"""6

Revision ID: 89f9cd22e930
Revises: 694f164681cf
Create Date: 2024-12-16 23:59:14.315992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '89f9cd22e930'
down_revision: Union[str, None] = '694f164681cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Identity_name', table_name='Identity')
    op.create_index(op.f('ix_Identity_name'), 'Identity', ['name'], unique=True)
    op.drop_index('ix_Proj_name', table_name='Proj')
    op.create_index(op.f('ix_Proj_name'), 'Proj', ['name'], unique=True)
    op.drop_index('ix_Resource_name', table_name='Resource')
    op.create_index(op.f('ix_Resource_name'), 'Resource', ['name'], unique=True)
    op.drop_index('ix_Team_name', table_name='Team')
    op.create_index(op.f('ix_Team_name'), 'Team', ['name'], unique=True)
    op.add_column('User', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_User_username', table_name='User')
    op.create_index(op.f('ix_User_name'), 'User', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_name'), table_name='User')
    op.create_index('ix_User_username', 'User', ['name'], unique=True)
    op.drop_column('User', 'description')
    op.drop_index(op.f('ix_Team_name'), table_name='Team')
    op.create_index('ix_Team_name', 'Team', ['name'], unique=False)
    op.drop_index(op.f('ix_Resource_name'), table_name='Resource')
    op.create_index('ix_Resource_name', 'Resource', ['name'], unique=False)
    op.drop_index(op.f('ix_Proj_name'), table_name='Proj')
    op.create_index('ix_Proj_name', 'Proj', ['name'], unique=False)
    op.drop_index(op.f('ix_Identity_name'), table_name='Identity')
    op.create_index('ix_Identity_name', 'Identity', ['name'], unique=False)
    # ### end Alembic commands ###
