import "./globals.css";
import { ThemeProvider } from '@/components/providers/theme-provider';
// import AuthProvider from './components/AuthProvider'

export const metadata = {
  title: "mcc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body 
      className={`antialiased`}
      suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          {/* <AuthProvider> */}
            {children}
          {/* </AuthProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
